@startuml
    skinparam backgroundColor transparent
    skinparam arrowColor #ffffff

    skinparam rectangleBackgroundColor #333
    skinparam rectangleBorderColor #ffcc00
    skinparam rectangleAttributeFontColor #fff
    skinparam rectangleFontColor #fff

    skinparam databaseBackgroundColor #ffcc00
    skinparam databaseBorderColor #000
    skinparam databaseAttributeFontColor #fff
    skinparam databaseFontColor #000
    skinparam databaseFontSize 20
    skinparam shadowing false

    skinparam defaultTextAlignment center

    database "Documentation" as d


    rectangle "**IBM DOORS**\nRequirement" as r #4A2213
    rectangle "**Atlassian JIRA**\nSpecification" as s #10184A
    rectangle "**Jetbrains IntelliJ**\nImplementation" as i #2B574F
    rectangle "**HP Quality Center**\nTest cases" as t #104561
    rectangle "**pytest**\nTest Reports" as tr #2E1061
    rectangle "**Sparxsystem EA**\nArchitecture" as a #500E57
    rectangle "**MS Word**\nRisk analysis" as ra #615C23
    rectangle "**Confluence**\nTechnology analysis" as ta #236127
    rectangle "**MS OneNote**\nMeeting minutes" as mm #611316


    r --> d
    s --> d
    i --> d
    t --> d

    tr -right-> d
    a -left-> d
    ra -up-> d
    ta -up-> d
    mm -up-> d

@enduml